version: "3.8"
services:
    app:
        container_name: reports-app
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "8000:8000"
            - "7000:7000"
            - "7001:7001"
            - "7002:7002"
            - "7003:7003"
        volumes:
            - ./:/var/www/html
            - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
        depends_on:
            - db
            - phpmyadmin
        networks:
            - lion
    db:
        image: mysql
        container_name: reports-mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - lion
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: reports-phpmyadmin
        restart: unless-stopped
        links:
            - db:db
        ports:
            - 8080:80
        environment:
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            - lion
volumes:
    mysql_data:
networks:
    lion:
        driver: bridge
